# Generated by Django 2.2.22 on 2023-03-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_filerepository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerepository',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='字节', null=True, verbose_name='文件大小'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='per_file_size',
            field=models.PositiveIntegerField(help_text='M', verbose_name='单文件大小(M)'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='project_space',
            field=models.PositiveIntegerField(help_text='G', verbose_name='单项目空间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='use_space',
            field=models.BigIntegerField(default=0, help_text='字节', verbose_name='项目已使用空间'),
        ),
    ]
