# Generated by Django 2.2.22 on 2023-04-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_issues_issuestype_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuestype',
            name='color',
        ),
    ]
